name: Health Check

on:
  schedule:
    - cron: '0 0 29 2 1'

jobs:
  periodic_health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Health Check
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-floral-leaf-4726.fly.dev
      - name: Notify Discord on Successful Health Check
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          text: 'Health Check'
          description: Pokedex is alive at https://full-stack-open-pokedex-floral-leaf-4726.fly.dev
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Notify Discord on Failed Health Check
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          text: 'Health Check'
          description: Pokedex is unreachable at https://full-stack-open-pokedex-floral-leaf-4726.fly.dev!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}