name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: ESLint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: E2E Tests
        run: npm run test:e2e
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 1
      - name: Setup Flyctl
        if: (github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip'))
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy
        id: deploy
        if: (github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip'))
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Notify Discord on Deployment
        uses: stegzilla/discord-notify@v2
        if: steps.deploy.outcome == 'success'
        with:
          colour: "#2cfc03"
          title: "A new version of Pokedex deployed"
          message: to https://full-stack-open-pokedex-floral-leaf-4726.fly.dev by ${{ github.actor }}
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Notify Discord on Failed Build
        uses: stegzilla/discord-notify@v2
        if: failure() && (github.event_name == 'push')
        with:
          colour: "#fc0303"
          title: "Build failed"
          message: commit ${{ github.event.head_commit.url }} by ${{ github.event.head_commit.author.username }} broke the build :(
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}

  tag_release:
    needs: [deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.67.0
      if: (github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip'))
      env:
        DEFAULT_BUMP: patch
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
